spring.profiles.active=dev
server.port=4200

spring.application.name=olva-integration-hub
spring.jpa.show-sql=true

spring.quartz.job-store-type=memory
spring.quartz.scheduler-name=olva-integration-hub-scheduler

integration.notification.dispatch.cron= */20 * * * * ?
integration.notification.batch-size=50
integration.notification.max-attempts=3
integration.notification.pending-state-id=9140
integration.notification.delivered-state-id=9142

logging.level.com.olva.notification=INFO


