spring.datasource.url=jdbc:oracle:thin:@10.10.10.110:1521:bdolva
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=olva_corp
spring.datasource.password=valicha

integration.ripley.token.cron=0 0/50 * * * ?
integration.ripley.orders.cron=0 */1 * * * ?
integration.ripley.auth.token-url=https://oauth.ripley.com/token
integration.ripley.auth.issuer=gerardo.arce@olva.com.pe
integration.ripley.auth.kid=YdQO52KYqEROKQ4WxQtJEw3tAiZ0GusU
integration.ripley.auth.scope=READ WRITE DELETE
integration.ripley.auth.private-key-path=/opt/integraciones/ripley/keys/private.pem
integration.ripley.auth.public-key-path=/opt/integraciones/ripley/keys/public.pem
integration.ripley.probe-on-startup=false
integration.ripley.notification.person-id=463595
integration.ripley.notification.tracking-url=https://api-pe-qa.ripley.com/retail/supply/transport/trazabilidad/v1/dispatchTracking
integration.ripley.notification.username=Olva
integration.ripley.notification.password=Olva2026$$
integration.serhafen.notification.tracking-url=
integration.serhafen.notification.api-key=
integration.serhafen.notification.executor-name=

integration.ripley.orders.url=https://api-pe-qa.ripley.com/retail/supply/transport/orderdelivery/v1/order/v3
integration.ripley.opl-code=OLVA
